export const ROUTES = {
  HOMEPAGE_ROUTE: '/',
  SIGNIN_ROUTE: '/user/signin',
  SIGNOUT_ROUTE: '/signout',
  REGISTER_ROUTE: '/signup',
  FLIPIMAGEPAGE_ROUTE: '/flipImage',
  COUNTDOWNPAGE_ROUTE: '/countdown/index',
  BLOGPAGE_ROUTE: '/blog',
  BLOGCATEGORY_ROUTE: '/blog/category',
  BLOGARTICLE_ROUTE: '/blog/article',
  PROBLEMS_ROUTE: '/subject/1',
  DETAILS_ROUTE: '/detail/1',
  GIPP_ROUTE: '/gipp',
  POKEMON_ROUTE: '/pokemon/pikachu',
}